version: "3.8"

services:
  backend:
    build: ./server
    container_name: mn-digital-backend
    ports:
      - 5005:5005
    env_file:
      - ./server/.env




  frontend:
    build: ./client
    container_name: mn-digital-frontend
    ports:
      - 5178:5173
    env_file:
      - ./client/.env

    depends_on:
      - backend    